# Generated by Django 4.2.7 on 2023-12-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
    ]
