# Generated by Django 4.2.7 on 2023-12-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userregistration_is_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number',
            field=models.CharField(default='00000000000', max_length=255),
        ),
    ]
